# PyTorch Tensor

In [2]:
import torch

# Tensor Allocation

In [5]:
#Float Tensor
ft = torch.FloatTensor([[1,2],
                      [3,4]])
ft

tensor([[1., 2.],
        [3., 4.]])

In [7]:
#Long Tensor
lt = torch.LongTensor([[1,2],
                      [3,4]])
lt
#index같은 값을 다룰 때 많이 사용

tensor([[1, 2],
        [3, 4]])

In [9]:
#Byte Tensor/Boolean Tensor도 존재
bt = torch.ByteTensor([[1,0],
                      [0,1]])
bt

tensor([[1, 0],
        [0, 1]], dtype=torch.uint8)

# Numpy Compatibility  
    :넘파이(배열)과 호환

In [15]:
import numpy as np
x = np.array([[1,2],
             [3,4]])
print(x, type(x))
#numpy.array 타입

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


In [16]:
#array to tensor
x = torch.from_numpy(x)
print(x, type(x))
#torch.tensor으로 변환

tensor([[1, 2],
        [3, 4]]) <class 'torch.Tensor'>


In [17]:
#tensor to array
x = x.numpy()
print(x, type(x))

[[1 2]
 [3 4]] <class 'numpy.ndarray'>


# Tensor type-casting  
    :같은 타입의 Tensor만 연산가능

In [18]:
ft.long()

tensor([[1, 2],
        [3, 4]])

In [19]:
ft.float()

tensor([[1., 2.],
        [3., 4.]])

In [20]:
torch.FloatTensor([1,0]).byte()

tensor([1, 0], dtype=torch.uint8)

# Get Shape

In [24]:
x = torch.FloatTensor([[[1,2],
                      [3,4]],
                     [[5,6],
                     [7,8]],
                      [[9,10],
                      [10,11]]])
print(x.size())
print(x.shape)

torch.Size([3, 2, 2])
torch.Size([3, 2, 2])


Get number of dimensios in the tensor.

In [25]:
print(x.dim())
print(len(x.size()))

3
3


Get number of elements in certain dimension of the tensor.

In [26]:
print(x.size(1))
print(x.shape[1])

2
2


Get number of elements in the last dimension.

In [28]:
print(x.size(-1))
print(x.shape[-1])

2
2
