# Gradient Descent  For Loss Minimization
    :기초적인 최적화 방법  
    :주어진 함수를 x로 미분하여 기울기를 활용. learning rate(step-size)와 함께 함수값(출력값)을 최소로 만드는 지점을 찾는 방법  
    :Loss function을 최소로하는 세타를 찾는다.  
    
    주의할 점 : Global Minima & Local Minima  
    그러나, 수 많은 차원에서 동시에 local minima를 위한 조건이 만족되기는 어려움.  
    
    learning rate는 이후 Adam optimizer를 통해서 해결가능하다!

In [2]:
import torch
import torch.nn.functional as F

In [3]:
target = torch.FloatTensor([[.1, .2, .3],
                            [.4, .5, .6],
                            [.7, .8, .9]])

In [4]:
x = torch.rand_like(target)
# This means the final scalar will be differentiate by x.
x.requires_grad = True
# AutoGrad
# You can get gradient of x, after differentiation.

x

tensor([[0.7280, 0.6265, 0.7596],
        [0.0148, 0.4087, 0.4797],
        [0.3359, 0.2179, 0.8097]], requires_grad=True)

In [4]:
loss = F.mse_loss(x, target)

loss

tensor(0.2058, grad_fn=<MseLossBackward>)

In [5]:
threshold = 1e-5
learning_rate = 1.
iter_cnt = 0

while loss > threshold:
    iter_cnt += 1
    
    loss.backward() # Calculate gradients.

    x = x - learning_rate * x.grad
    
    x.detach_()
    x.requires_grad_(True)
    
    loss = F.mse_loss(x, target)
    
    print('%d-th Loss: %.4e' % (iter_cnt, loss))
    print(x)

1-th Loss: 1.2450e-01
tensor([[0.6984, 0.5182, 0.4612],
        [0.7033, 0.3670, 0.6659],
        [0.4502, 0.2685, 0.4801]], requires_grad=True)
2-th Loss: 7.5312e-02
tensor([[0.5654, 0.4475, 0.4253],
        [0.6359, 0.3966, 0.6512],
        [0.5057, 0.3866, 0.5734]], requires_grad=True)
3-th Loss: 4.5559e-02
tensor([[0.4620, 0.3925, 0.3975],
        [0.5835, 0.4196, 0.6398],
        [0.5489, 0.4785, 0.6460]], requires_grad=True)
4-th Loss: 2.7560e-02
tensor([[0.3815, 0.3497, 0.3758],
        [0.5427, 0.4374, 0.6310],
        [0.5825, 0.5499, 0.7024]], requires_grad=True)
5-th Loss: 1.6672e-02
tensor([[0.3190, 0.3164, 0.3590],
        [0.5110, 0.4513, 0.6241],
        [0.6086, 0.6055, 0.7463]], requires_grad=True)
6-th Loss: 1.0086e-02
tensor([[0.2703, 0.2906, 0.3459],
        [0.4863, 0.4621, 0.6187],
        [0.6289, 0.6487, 0.7805]], requires_grad=True)
7-th Loss: 6.1012e-03
tensor([[0.2325, 0.2704, 0.3357],
        [0.4671, 0.4706, 0.6146],
        [0.6447, 0.6823, 0.8070]], requi